# Generated by Django 4.1 on 2022-08-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_noticias_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='text_noticia',
            field=models.TextField(default='Texto', max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='author',
            field=models.CharField(default='Autor', max_length=50),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='resume_noticia',
            field=models.CharField(default='Resumo', max_length=200),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='title_noticia',
            field=models.CharField(default='Título', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
