# Generated by Django 4.1 on 2022-08-19 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_noticias_text_noticia_alter_noticias_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='resume_noticia',
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='text_noticia',
        ),
        migrations.AlterField(
            model_name='noticias',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
