# Generated by Django 4.1 on 2022-08-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_noticias_resume_noticia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa'),
        ),
    ]
