# Generated by Django 4.1 on 2022-08-22 12:18

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_noticias_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='resume_noticia',
            field=models.CharField(default='resumo', max_length=100),
        ),
        migrations.AddField(
            model_name='noticias',
            name='text_noticia',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Texto'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
