# Generated by Django 4.1 on 2022-08-23 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_noticias_resume_noticia_noticias_text_noticia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='Blog',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='resume_noticia',
            new_name='resume_post',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='text_noticia',
            new_name='text_post',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title_noticia',
            new_name='title_post',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='descricao_pessoa',
            field=models.CharField(default='Breve descricao para o site', max_length=500),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cargo',
            field=models.CharField(default='Cargo', max_length=50),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf_pessoa',
            field=models.CharField(default='000.000.000-00', max_length=500),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_pessoa',
            field=models.CharField(default='Nome pessoa', max_length=500),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_produto',
            field=models.CharField(default='Breve descricao produto', max_length=200),
        ),
    ]
